/*
  # ADA System Schema Integration

  Adapted from `db_ada.sql`.
  - Renamed tables with `ada_` prefix to avoid conflicts with existing `stages`/`challenges` tables.
  - Corrected syntax errors (e.g., `interger` -> `integer`).
  - Adjusted Foreign Key logic to standard practices (Join tables reference entities).
  - Use `GENERATED BY DEFAULT AS IDENTITY` for AUTO_INCREMENT equivalent in Postgres.
  - Primary Keys are NOT NULL (implicit).
  - Other fields are nullable (default).
*/

-- 1. Users (renamed to ada_users to avoid reserved word conflict)
CREATE TABLE IF NOT EXISTS "ada_users" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "correo" varchar,
  "dispositivo" varchar,
  "created_at" timestamp DEFAULT now(),
  "update_at" timestamp DEFAULT now()
);

-- 2. Type Selection
CREATE TABLE IF NOT EXISTS "ada_type_selection" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar
);

-- 3. Stages (renamed to ada_stages)
CREATE TABLE IF NOT EXISTS "ada_stages" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar
);

-- 4. Cards (renamed to ada_cards)
CREATE TABLE IF NOT EXISTS "ada_cards" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "stage_id" integer REFERENCES "ada_stages" ("id"),
  "name" varchar
);

-- 5. Stages Cards (Join table / Relationship)
CREATE TABLE IF NOT EXISTS "ada_stages_cards" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "stage_id" integer REFERENCES "ada_stages" ("id"),
  "card_id" integer REFERENCES "ada_cards" ("id")
);

-- 6. User Selection (Main interaction table)
CREATE TABLE IF NOT EXISTS "ada_user_selection" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer REFERENCES "ada_users" ("id"),
  "type_selection_id" integer REFERENCES "ada_type_selection" ("id"),
  "stages_cards_id" integer REFERENCES "ada_stages_cards" ("id"),
  "res_user" json,
  "created_at" timestamp DEFAULT now(),
  "update_at" timestamp DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_ada_cards_stage_id ON "ada_cards" ("stage_id");
CREATE INDEX IF NOT EXISTS idx_ada_user_selection_user_id ON "ada_user_selection" ("user_id");
