-- Create table for per-stage progress tracking
CREATE TABLE IF NOT EXISTS "ada_user_stage_progress" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer REFERENCES "ada_users" ("id") ON DELETE CASCADE,
  "stage_number" integer NOT NULL,
  "last_card_index" integer DEFAULT 0,
  "complete_date" timestamp,
  "created_at" timestamp DEFAULT now(),
  "update_at" timestamp DEFAULT now(),
  UNIQUE("user_id", "stage_number")
);

-- Cleanup old columns from ada_users
ALTER TABLE "ada_users" DROP COLUMN IF EXISTS "current_stage_number";
ALTER TABLE "ada_users" DROP COLUMN IF EXISTS "last_card_index";
